source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 5.2'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'faker'
gem 'dotenv', '~> 2.7'
gem 'rack-flash3', '~>1.0'
gem 'regex', '~> 1.1', '>= 1.1.1'


group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
end
